# -*- coding: utf-8 -*-
# IATA: (ville, nom aéroport, pays ISO2, lat, lon, fuseau IANA, rang hub 1..3)
# rang 1 = grand hub international, 2 = aéroport majeur, 3 = régional

A = {
# ---------------- FRANCE ----------------
"CDG": ("Paris", "Charles de Gaulle", "FR", 49.01, 2.55, "Europe/Paris", 1),
"ORY": ("Paris", "Orly", "FR", 48.72, 2.38, "Europe/Paris", 2),
"NCE": ("Nice", "Côte d'Azur", "FR", 43.66, 7.22, "Europe/Paris", 2),
"LYS": ("Lyon", "Saint-Exupéry", "FR", 45.73, 5.08, "Europe/Paris", 2),
"MRS": ("Marseille", "Provence", "FR", 43.44, 5.22, "Europe/Paris", 2),
"TLS": ("Toulouse", "Blagnac", "FR", 43.63, 1.37, "Europe/Paris", 2),
"BOD": ("Bordeaux", "Mérignac", "FR", 44.83, -0.72, "Europe/Paris", 2),
"NTE": ("Nantes", "Atlantique", "FR", 47.16, -1.61, "Europe/Paris", 2),
"LIL": ("Lille", "Lesquin", "FR", 50.56, 3.09, "Europe/Paris", 3),
"SXB": ("Strasbourg", "Entzheim", "FR", 48.54, 7.63, "Europe/Paris", 3),
"MPL": ("Montpellier", "Méditerranée", "FR", 43.58, 3.96, "Europe/Paris", 3),
"BIQ": ("Biarritz", "Pays Basque", "FR", 43.47, -1.52, "Europe/Paris", 3),
"AJA": ("Ajaccio", "Napoléon Bonaparte", "FR", 41.92, 8.80, "Europe/Paris", 3),
"BIA": ("Bastia", "Poretta", "FR", 42.55, 9.48, "Europe/Paris", 3),
"BES": ("Brest", "Bretagne", "FR", 48.45, -4.42, "Europe/Paris", 3),
"RNS": ("Rennes", "Saint-Jacques", "FR", 48.07, -1.73, "Europe/Paris", 3),
"CFE": ("Clermont-Ferrand", "Auvergne", "FR", 45.79, 3.17, "Europe/Paris", 3),
"PUF": ("Pau", "Pyrénées", "FR", 43.38, -0.42, "Europe/Paris", 3),
"RUN": ("Saint-Denis", "Roland Garros", "FR", -20.89, 55.52, "Indian/Reunion", 2),
"PTP": ("Pointe-à-Pitre", "Le Raizet", "FR", 16.27, -61.53, "America/Guadeloupe", 3),
"FDF": ("Fort-de-France", "Aimé Césaire", "FR", 14.59, -61.00, "America/Martinique", 3),
"PPT": ("Papeete", "Faa'a", "FR", -17.56, -149.61, "Pacific/Tahiti", 3),

# ---------------- ESPAGNE ----------------
"MAD": ("Madrid", "Barajas", "ES", 40.47, -3.56, "Europe/Madrid", 1),
"BCN": ("Barcelone", "El Prat", "ES", 41.30, 2.08, "Europe/Madrid", 1),
"AGP": ("Malaga", "Costa del Sol", "ES", 36.67, -4.50, "Europe/Madrid", 2),
"PMI": ("Palma", "Son Sant Joan", "ES", 39.55, 2.74, "Europe/Madrid", 2),
"ALC": ("Alicante", "Elche", "ES", 38.28, -0.56, "Europe/Madrid", 2),
"VLC": ("Valence", "Manises", "ES", 39.49, -0.48, "Europe/Madrid", 2),
"SVQ": ("Séville", "San Pablo", "ES", 37.42, -5.90, "Europe/Madrid", 3),
"BIO": ("Bilbao", "Loiu", "ES", 43.30, -2.91, "Europe/Madrid", 3),
"IBZ": ("Ibiza", "Ibiza", "ES", 38.87, 1.37, "Europe/Madrid", 3),
"LPA": ("Las Palmas", "Gran Canaria", "ES", 27.93, -15.39, "Atlantic/Canary", 2),
"TFS": ("Tenerife", "Tenerife Sud", "ES", 28.04, -16.57, "Atlantic/Canary", 2),
"ACE": ("Lanzarote", "César Manrique", "ES", 28.95, -13.61, "Atlantic/Canary", 3),
"FUE": ("Fuerteventura", "Fuerteventura", "ES", 28.45, -13.86, "Atlantic/Canary", 3),
"SCQ": ("Saint-Jacques-de-Compostelle", "Lavacolla", "ES", 42.90, -8.42, "Europe/Madrid", 3),

# ---------------- ITALIE ----------------
"FCO": ("Rome", "Fiumicino", "IT", 41.80, 12.25, "Europe/Rome", 1),
"MXP": ("Milan", "Malpensa", "IT", 45.63, 8.73, "Europe/Rome", 1),
"LIN": ("Milan", "Linate", "IT", 45.45, 9.28, "Europe/Rome", 2),
"BGY": ("Milan", "Orio al Serio", "IT", 45.67, 9.70, "Europe/Rome", 3),
"VCE": ("Venise", "Marco Polo", "IT", 45.51, 12.35, "Europe/Rome", 2),
"NAP": ("Naples", "Capodichino", "IT", 40.89, 14.29, "Europe/Rome", 2),
"BLQ": ("Bologne", "Guglielmo Marconi", "IT", 44.53, 11.30, "Europe/Rome", 3),
"CTA": ("Catane", "Fontanarossa", "IT", 37.47, 15.07, "Europe/Rome", 3),
"PMO": ("Palerme", "Falcone Borsellino", "IT", 38.18, 13.10, "Europe/Rome", 3),
"FLR": ("Florence", "Peretola", "IT", 43.81, 11.21, "Europe/Rome", 3),
"TRN": ("Turin", "Caselle", "IT", 45.20, 7.65, "Europe/Rome", 3),
"BRI": ("Bari", "Karol Wojtyła", "IT", 41.14, 16.76, "Europe/Rome", 3),
"PSA": ("Pise", "Galileo Galilei", "IT", 43.68, 10.39, "Europe/Rome", 3),
"CAG": ("Cagliari", "Elmas", "IT", 39.25, 9.05, "Europe/Rome", 3),

# ---------------- ALLEMAGNE ----------------
"FRA": ("Francfort", "Francfort-sur-le-Main", "DE", 50.03, 8.57, "Europe/Berlin", 1),
"MUC": ("Munich", "Franz Josef Strauss", "DE", 48.35, 11.79, "Europe/Berlin", 1),
"BER": ("Berlin", "Brandenburg", "DE", 52.36, 13.51, "Europe/Berlin", 1),
"DUS": ("Düsseldorf", "Düsseldorf", "DE", 51.29, 6.77, "Europe/Berlin", 2),
"HAM": ("Hambourg", "Fuhlsbüttel", "DE", 53.63, 10.01, "Europe/Berlin", 2),
"CGN": ("Cologne", "Cologne-Bonn", "DE", 50.87, 7.14, "Europe/Berlin", 3),
"STR": ("Stuttgart", "Stuttgart", "DE", 48.69, 9.22, "Europe/Berlin", 3),
"HAJ": ("Hanovre", "Langenhagen", "DE", 52.46, 9.69, "Europe/Berlin", 3),
"NUE": ("Nuremberg", "Nuremberg", "DE", 49.50, 11.08, "Europe/Berlin", 3),
"LEJ": ("Leipzig", "Halle", "DE", 51.42, 12.24, "Europe/Berlin", 3),

# ---------------- ROYAUME-UNI ----------------
"LHR": ("Londres", "Heathrow", "GB", 51.47, -0.45, "Europe/London", 1),
"LGW": ("Londres", "Gatwick", "GB", 51.15, -0.19, "Europe/London", 1),
"STN": ("Londres", "Stansted", "GB", 51.89, 0.24, "Europe/London", 2),
"LTN": ("Londres", "Luton", "GB", 51.87, -0.37, "Europe/London", 3),
"LCY": ("Londres", "City", "GB", 51.51, 0.05, "Europe/London", 3),
"MAN": ("Manchester", "Manchester", "GB", 53.35, -2.27, "Europe/London", 2),
"EDI": ("Édimbourg", "Édimbourg", "GB", 55.95, -3.37, "Europe/London", 2),
"BHX": ("Birmingham", "Birmingham", "GB", 52.45, -1.75, "Europe/London", 3),
"GLA": ("Glasgow", "Glasgow", "GB", 55.87, -4.43, "Europe/London", 3),
"BRS": ("Bristol", "Bristol", "GB", 51.38, -2.72, "Europe/London", 3),
"NCL": ("Newcastle", "Newcastle", "GB", 55.04, -1.69, "Europe/London", 3),
"BFS": ("Belfast", "Belfast International", "GB", 54.66, -6.22, "Europe/London", 3),

# ---------------- GRÈCE ----------------
"ATH": ("Athènes", "Elefthérios-Venizélos", "GR", 37.94, 23.95, "Europe/Athens", 1),
"SKG": ("Thessalonique", "Macédoine", "GR", 40.52, 22.97, "Europe/Athens", 2),
"HER": ("Héraklion", "Níkos-Kazantzákis", "GR", 35.34, 25.18, "Europe/Athens", 2),
"RHO": ("Rhodes", "Diagóras", "GR", 36.41, 28.09, "Europe/Athens", 3),
"CHQ": ("La Canée", "Ioánnis-Daskalogiánnis", "GR", 35.53, 24.15, "Europe/Athens", 3),
"JTR": ("Santorin", "Santorin", "GR", 36.40, 25.48, "Europe/Athens", 3),
"JMK": ("Mykonos", "Mykonos", "GR", 37.44, 25.35, "Europe/Athens", 3),
"CFU": ("Corfou", "Ioánnis-Kapodístrias", "GR", 39.60, 19.91, "Europe/Athens", 3),
"KGS": ("Kos", "Hippocrate", "GR", 36.79, 27.09, "Europe/Athens", 3),
"ZTH": ("Zante", "Dionýsios-Solomós", "GR", 37.75, 20.88, "Europe/Athens", 3),

# ---------------- PORTUGAL / BENELUX / SUISSE / AUTRICHE ----------------
"LIS": ("Lisbonne", "Humberto Delgado", "PT", 38.77, -9.13, "Europe/Lisbon", 1),
"OPO": ("Porto", "Francisco Sá Carneiro", "PT", 41.24, -8.68, "Europe/Lisbon", 2),
"FAO": ("Faro", "Faro", "PT", 37.01, -7.97, "Europe/Lisbon", 3),
"FNC": ("Funchal", "Cristiano Ronaldo", "PT", 32.69, -16.78, "Atlantic/Madeira", 3),
"PDL": ("Ponta Delgada", "João Paulo II", "PT", 37.74, -25.70, "Atlantic/Azores", 3),
"AMS": ("Amsterdam", "Schiphol", "NL", 52.31, 4.76, "Europe/Amsterdam", 1),
"EIN": ("Eindhoven", "Eindhoven", "NL", 51.45, 5.37, "Europe/Amsterdam", 3),
"RTM": ("Rotterdam", "La Haye", "NL", 51.95, 4.44, "Europe/Amsterdam", 3),
"BRU": ("Bruxelles", "Zaventem", "BE", 50.90, 4.48, "Europe/Brussels", 1),
"CRL": ("Charleroi", "Bruxelles-Sud", "BE", 50.46, 4.45, "Europe/Brussels", 3),
"ZRH": ("Zurich", "Kloten", "CH", 47.46, 8.55, "Europe/Zurich", 1),
"GVA": ("Genève", "Cointrin", "CH", 46.24, 6.11, "Europe/Zurich", 2),
"BSL": ("Bâle", "Mulhouse", "CH", 47.59, 7.53, "Europe/Zurich", 3),
"VIE": ("Vienne", "Schwechat", "AT", 48.11, 16.57, "Europe/Vienna", 1),
"SZG": ("Salzbourg", "W. A. Mozart", "AT", 47.79, 13.00, "Europe/Vienna", 3),
"INN": ("Innsbruck", "Innsbruck", "AT", 47.26, 11.34, "Europe/Vienna", 3),
"LUX": ("Luxembourg", "Findel", "LU", 49.63, 6.21, "Europe/Luxembourg", 3),

# ---------------- IRLANDE / NORDIQUES / BALTES ----------------
"DUB": ("Dublin", "Dublin", "IE", 53.43, -6.27, "Europe/Dublin", 1),
"ORK": ("Cork", "Cork", "IE", 51.84, -8.49, "Europe/Dublin", 3),
"SNN": ("Shannon", "Shannon", "IE", 52.70, -8.92, "Europe/Dublin", 3),
"CPH": ("Copenhague", "Kastrup", "DK", 55.62, 12.66, "Europe/Copenhagen", 1),
"BLL": ("Billund", "Billund", "DK", 55.74, 9.15, "Europe/Copenhagen", 3),
"ARN": ("Stockholm", "Arlanda", "SE", 59.65, 17.92, "Europe/Stockholm", 1),
"GOT": ("Göteborg", "Landvetter", "SE", 57.66, 12.29, "Europe/Stockholm", 3),
"OSL": ("Oslo", "Gardermoen", "NO", 60.19, 11.10, "Europe/Oslo", 1),
"BGO": ("Bergen", "Flesland", "NO", 60.29, 5.22, "Europe/Oslo", 3),
"TRD": ("Trondheim", "Værnes", "NO", 63.46, 10.92, "Europe/Oslo", 3),
"HEL": ("Helsinki", "Vantaa", "FI", 60.32, 24.96, "Europe/Helsinki", 1),
"KEF": ("Reykjavik", "Keflavík", "IS", 63.99, -22.61, "Atlantic/Reykjavik", 2),
"TLL": ("Tallinn", "Lennart Meri", "EE", 59.41, 24.83, "Europe/Tallinn", 3),
"RIX": ("Riga", "Riga", "LV", 56.92, 23.97, "Europe/Riga", 3),
"VNO": ("Vilnius", "Vilnius", "LT", 54.64, 25.29, "Europe/Vilnius", 3),

# ---------------- EUROPE CENTRALE ET DU SUD-EST ----------------
"WAW": ("Varsovie", "Chopin", "PL", 52.17, 20.97, "Europe/Warsaw", 1),
"KRK": ("Cracovie", "Jean-Paul II", "PL", 50.08, 19.80, "Europe/Warsaw", 2),
"GDN": ("Gdansk", "Lech Wałęsa", "PL", 54.38, 18.47, "Europe/Warsaw", 3),
"WRO": ("Wrocław", "Copernic", "PL", 51.10, 16.89, "Europe/Warsaw", 3),
"KTW": ("Katowice", "Pyrzowice", "PL", 50.47, 19.08, "Europe/Warsaw", 3),
"PRG": ("Prague", "Václav Havel", "CZ", 50.10, 14.26, "Europe/Prague", 1),
"BRQ": ("Brno", "Tuřany", "CZ", 49.15, 16.69, "Europe/Prague", 3),
"BUD": ("Budapest", "Ferenc Liszt", "HU", 47.44, 19.26, "Europe/Budapest", 1),
"OTP": ("Bucarest", "Henri Coandă", "RO", 44.57, 26.10, "Europe/Bucharest", 1),
"CLJ": ("Cluj-Napoca", "Avram Iancu", "RO", 46.79, 23.69, "Europe/Bucharest", 3),
"SOF": ("Sofia", "Sofia", "BG", 42.69, 23.41, "Europe/Sofia", 2),
"VAR": ("Varna", "Varna", "BG", 43.23, 27.83, "Europe/Sofia", 3),
"ZAG": ("Zagreb", "Franjo Tuđman", "HR", 45.74, 16.07, "Europe/Zagreb", 2),
"SPU": ("Split", "Split", "HR", 43.54, 16.30, "Europe/Zagreb", 3),
"DBV": ("Dubrovnik", "Dubrovnik", "HR", 42.56, 18.27, "Europe/Zagreb", 3),
"BEG": ("Belgrade", "Nikola Tesla", "RS", 44.82, 20.31, "Europe/Belgrade", 2),
"BTS": ("Bratislava", "M. R. Štefánik", "SK", 48.17, 17.21, "Europe/Bratislava", 3),
"LJU": ("Ljubljana", "Jože Pučnik", "SI", 46.22, 14.46, "Europe/Ljubljana", 3),
"TIA": ("Tirana", "Mère Teresa", "AL", 41.41, 19.72, "Europe/Tirane", 3),
"SKP": ("Skopje", "Skopje", "MK", 41.96, 21.62, "Europe/Skopje", 3),
"MLA": ("La Valette", "Malte", "MT", 35.86, 14.48, "Europe/Malta", 3),
"LCA": ("Larnaca", "Larnaca", "CY", 34.88, 33.63, "Asia/Nicosia", 2),
"PFO": ("Paphos", "Paphos", "CY", 34.72, 32.49, "Asia/Nicosia", 3),

# ---------------- TURQUIE / RUSSIE ----------------
"IST": ("Istanbul", "Istanbul", "TR", 41.26, 28.74, "Europe/Istanbul", 1),
"SAW": ("Istanbul", "Sabiha Gökçen", "TR", 40.90, 29.31, "Europe/Istanbul", 2),
"AYT": ("Antalya", "Antalya", "TR", 36.90, 30.79, "Europe/Istanbul", 2),
"ADB": ("Izmir", "Adnan Menderes", "TR", 38.29, 27.16, "Europe/Istanbul", 3),
"ESB": ("Ankara", "Esenboğa", "TR", 40.13, 32.995, "Europe/Istanbul", 3),
"BJV": ("Bodrum", "Milas", "TR", 37.25, 27.66, "Europe/Istanbul", 3),
"SVO": ("Moscou", "Cheremetievo", "RU", 55.97, 37.41, "Europe/Moscow", 1),
"DME": ("Moscou", "Domodedovo", "RU", 55.41, 37.90, "Europe/Moscow", 2),
"LED": ("Saint-Pétersbourg", "Poulkovo", "RU", 59.80, 30.26, "Europe/Moscow", 2),

# ---------------- ÉTATS-UNIS ----------------
"JFK": ("New York", "John F. Kennedy", "US", 40.64, -73.78, "America/New_York", 1),
"EWR": ("Newark", "Liberty", "US", 40.69, -74.17, "America/New_York", 1),
"LGA": ("New York", "LaGuardia", "US", 40.78, -73.87, "America/New_York", 2),
"BOS": ("Boston", "Logan", "US", 42.36, -71.01, "America/New_York", 2),
"IAD": ("Washington", "Dulles", "US", 38.95, -77.46, "America/New_York", 2),
"DCA": ("Washington", "Reagan National", "US", 38.85, -77.04, "America/New_York", 3),
"PHL": ("Philadelphie", "Philadelphie", "US", 39.87, -75.24, "America/New_York", 3),
"MIA": ("Miami", "Miami", "US", 25.79, -80.29, "America/New_York", 1),
"MCO": ("Orlando", "Orlando", "US", 28.43, -81.31, "America/New_York", 2),
"TPA": ("Tampa", "Tampa", "US", 27.98, -82.53, "America/New_York", 3),
"ATL": ("Atlanta", "Hartsfield-Jackson", "US", 33.64, -84.43, "America/New_York", 1),
"CLT": ("Charlotte", "Douglas", "US", 35.21, -80.94, "America/New_York", 3),
"DTW": ("Détroit", "Metropolitan", "US", 42.21, -83.35, "America/New_York", 3),
"ORD": ("Chicago", "O'Hare", "US", 41.98, -87.90, "America/Chicago", 1),
"DFW": ("Dallas", "Fort Worth", "US", 32.90, -97.04, "America/Chicago", 1),
"IAH": ("Houston", "Bush Intercontinental", "US", 29.98, -95.34, "America/Chicago", 2),
"MSP": ("Minneapolis", "Saint-Paul", "US", 44.88, -93.22, "America/Chicago", 3),
"DEN": ("Denver", "Denver", "US", 39.86, -104.67, "America/Denver", 2),
"PHX": ("Phoenix", "Sky Harbor", "US", 33.43, -112.01, "America/Phoenix", 3),
"LAS": ("Las Vegas", "Harry Reid", "US", 36.08, -115.15, "America/Los_Angeles", 2),
"LAX": ("Los Angeles", "Los Angeles", "US", 33.94, -118.41, "America/Los_Angeles", 1),
"SFO": ("San Francisco", "San Francisco", "US", 37.62, -122.38, "America/Los_Angeles", 1),
"SAN": ("San Diego", "San Diego", "US", 32.73, -117.19, "America/Los_Angeles", 3),
"SEA": ("Seattle", "Tacoma", "US", 47.45, -122.31, "America/Los_Angeles", 2),
"HNL": ("Honolulu", "Daniel K. Inouye", "US", 21.32, -157.92, "Pacific/Honolulu", 3),

# ---------------- CANADA / MEXIQUE / CARAÏBES ----------------
"YYZ": ("Toronto", "Pearson", "CA", 43.68, -79.63, "America/Toronto", 1),
"YUL": ("Montréal", "Trudeau", "CA", 45.47, -73.74, "America/Toronto", 1),
"YOW": ("Ottawa", "Macdonald-Cartier", "CA", 45.32, -75.67, "America/Toronto", 3),
"YVR": ("Vancouver", "Vancouver", "CA", 49.19, -123.18, "America/Vancouver", 1),
"YYC": ("Calgary", "Calgary", "CA", 51.11, -114.02, "America/Edmonton", 2),
"YEG": ("Edmonton", "Edmonton", "CA", 53.31, -113.58, "America/Edmonton", 3),
"MEX": ("Mexico", "Benito Juárez", "MX", 19.44, -99.07, "America/Mexico_City", 1),
"CUN": ("Cancún", "Cancún", "MX", 21.04, -86.87, "America/Cancun", 2),
"GDL": ("Guadalajara", "Miguel Hidalgo", "MX", 20.52, -103.31, "America/Mexico_City", 3),
"MTY": ("Monterrey", "Monterrey", "MX", 25.78, -100.11, "America/Monterrey", 3),
"HAV": ("La Havane", "José Martí", "CU", 22.99, -82.41, "America/Havana", 3),
"PUJ": ("Punta Cana", "Punta Cana", "DO", 18.57, -68.36, "America/Santo_Domingo", 3),
"SDQ": ("Saint-Domingue", "Las Américas", "DO", 18.43, -69.67, "America/Santo_Domingo", 3),
"PTY": ("Panama", "Tocumen", "PA", 9.07, -79.38, "America/Panama", 2),
"SJO": ("San José", "Juan Santamaría", "CR", 9.99, -84.21, "America/Costa_Rica", 3),

# ---------------- AMÉRIQUE DU SUD ----------------
"GRU": ("São Paulo", "Guarulhos", "BR", -23.43, -46.47, "America/Sao_Paulo", 1),
"GIG": ("Rio de Janeiro", "Galeão", "BR", -22.81, -43.25, "America/Sao_Paulo", 1),
"BSB": ("Brasilia", "Juscelino Kubitschek", "BR", -15.87, -47.92, "America/Sao_Paulo", 2),
"CNF": ("Belo Horizonte", "Confins", "BR", -19.62, -43.97, "America/Sao_Paulo", 3),
"SSA": ("Salvador", "Deputado Luís Eduardo", "BR", -12.91, -38.33, "America/Bahia", 3),
"REC": ("Recife", "Guararapes", "BR", -8.13, -34.92, "America/Recife", 3),
"FOR": ("Fortaleza", "Pinto Martins", "BR", -3.78, -38.53, "America/Fortaleza", 3),
"POA": ("Porto Alegre", "Salgado Filho", "BR", -29.99, -51.17, "America/Sao_Paulo", 3),
"EZE": ("Buenos Aires", "Ezeiza", "AR", -34.82, -58.54, "America/Argentina/Buenos_Aires", 1),
"AEP": ("Buenos Aires", "Jorge Newbery", "AR", -34.56, -58.42, "America/Argentina/Buenos_Aires", 3),
"COR": ("Córdoba", "Pajas Blancas", "AR", -31.32, -64.21, "America/Argentina/Cordoba", 3),
"SCL": ("Santiago", "Arturo Merino Benítez", "CL", -33.39, -70.79, "America/Santiago", 1),
"LIM": ("Lima", "Jorge Chávez", "PE", -12.02, -77.11, "America/Lima", 1),
"BOG": ("Bogota", "El Dorado", "CO", 4.70, -74.15, "America/Bogota", 1),
"MDE": ("Medellín", "José María Córdova", "CO", 6.16, -75.42, "America/Bogota", 3),
"CTG": ("Carthagène", "Rafael Núñez", "CO", 10.44, -75.51, "America/Bogota", 3),
"UIO": ("Quito", "Mariscal Sucre", "EC", -0.13, -78.36, "America/Guayaquil", 3),
"GYE": ("Guayaquil", "José Joaquín de Olmedo", "EC", -2.16, -79.88, "America/Guayaquil", 3),
"MVD": ("Montevideo", "Carrasco", "UY", -34.84, -56.03, "America/Montevideo", 3),

# ---------------- JAPON / CORÉE / CHINE ----------------
"HND": ("Tokyo", "Haneda", "JP", 35.55, 139.78, "Asia/Tokyo", 1),
"NRT": ("Tokyo", "Narita", "JP", 35.77, 140.39, "Asia/Tokyo", 1),
"KIX": ("Osaka", "Kansai", "JP", 34.43, 135.24, "Asia/Tokyo", 2),
"ITM": ("Osaka", "Itami", "JP", 34.79, 135.44, "Asia/Tokyo", 3),
"CTS": ("Sapporo", "New Chitose", "JP", 42.78, 141.69, "Asia/Tokyo", 3),
"FUK": ("Fukuoka", "Fukuoka", "JP", 33.59, 130.45, "Asia/Tokyo", 3),
"NGO": ("Nagoya", "Chubu Centrair", "JP", 34.86, 136.81, "Asia/Tokyo", 3),
"OKA": ("Okinawa", "Naha", "JP", 26.20, 127.65, "Asia/Tokyo", 3),
"ICN": ("Séoul", "Incheon", "KR", 37.46, 126.44, "Asia/Seoul", 1),
"GMP": ("Séoul", "Gimpo", "KR", 37.56, 126.80, "Asia/Seoul", 3),
"PUS": ("Busan", "Gimhae", "KR", 35.18, 128.94, "Asia/Seoul", 3),
"PEK": ("Pékin", "Capital", "CN", 40.08, 116.58, "Asia/Shanghai", 1),
"PKX": ("Pékin", "Daxing", "CN", 39.51, 116.41, "Asia/Shanghai", 2),
"PVG": ("Shanghai", "Pudong", "CN", 31.14, 121.81, "Asia/Shanghai", 1),
"SHA": ("Shanghai", "Hongqiao", "CN", 31.20, 121.34, "Asia/Shanghai", 3),
"CAN": ("Canton", "Baiyun", "CN", 23.39, 113.31, "Asia/Shanghai", 1),
"SZX": ("Shenzhen", "Bao'an", "CN", 22.64, 113.81, "Asia/Shanghai", 2),
"CTU": ("Chengdu", "Tianfu", "CN", 30.31, 104.44, "Asia/Shanghai", 2),
"XIY": ("Xi'an", "Xianyang", "CN", 34.45, 108.75, "Asia/Shanghai", 3),
"HGH": ("Hangzhou", "Xiaoshan", "CN", 30.23, 120.43, "Asia/Shanghai", 3),
"KMG": ("Kunming", "Changshui", "CN", 25.11, 102.93, "Asia/Shanghai", 3),
"HKG": ("Hong Kong", "Chek Lap Kok", "HK", 22.31, 113.91, "Asia/Hong_Kong", 1),
"MFM": ("Macao", "Macao", "MO", 22.15, 113.59, "Asia/Macau", 3),
"TPE": ("Taipei", "Taoyuan", "TW", 25.08, 121.23, "Asia/Taipei", 1),
"KHH": ("Kaohsiung", "Kaohsiung", "TW", 22.58, 120.35, "Asia/Taipei", 3),

# ---------------- ASIE DU SUD-EST ----------------
"SIN": ("Singapour", "Changi", "SG", 1.36, 103.99, "Asia/Singapore", 1),
"BKK": ("Bangkok", "Suvarnabhumi", "TH", 13.69, 100.75, "Asia/Bangkok", 1),
"DMK": ("Bangkok", "Don Mueang", "TH", 13.91, 100.61, "Asia/Bangkok", 3),
"HKT": ("Phuket", "Phuket", "TH", 8.11, 98.31, "Asia/Bangkok", 2),
"CNX": ("Chiang Mai", "Chiang Mai", "TH", 18.77, 98.96, "Asia/Bangkok", 3),
"KUL": ("Kuala Lumpur", "KLIA", "MY", 2.75, 101.71, "Asia/Kuala_Lumpur", 1),
"PEN": ("Penang", "Penang", "MY", 5.30, 100.28, "Asia/Kuala_Lumpur", 3),
"BKI": ("Kota Kinabalu", "Kota Kinabalu", "MY", 5.94, 116.05, "Asia/Kuala_Lumpur", 3),
"CGK": ("Jakarta", "Soekarno-Hatta", "ID", -6.13, 106.66, "Asia/Jakarta", 1),
"DPS": ("Bali", "Ngurah Rai", "ID", -8.75, 115.17, "Asia/Makassar", 2),
"SUB": ("Surabaya", "Juanda", "ID", -7.38, 112.79, "Asia/Jakarta", 3),
"MNL": ("Manille", "Ninoy Aquino", "PH", 14.51, 121.02, "Asia/Manila", 1),
"CEB": ("Cebu", "Mactan", "PH", 10.31, 123.98, "Asia/Manila", 3),
"SGN": ("Hô Chi Minh-Ville", "Tân Sơn Nhất", "VN", 10.82, 106.66, "Asia/Ho_Chi_Minh", 1),
"HAN": ("Hanoï", "Nội Bài", "VN", 21.22, 105.81, "Asia/Ho_Chi_Minh", 2),
"DAD": ("Da Nang", "Da Nang", "VN", 16.04, 108.20, "Asia/Ho_Chi_Minh", 3),
"PNH": ("Phnom Penh", "Phnom Penh", "KH", 11.55, 104.84, "Asia/Phnom_Penh", 3),
"RGN": ("Rangoun", "Yangon", "MM", 16.91, 96.13, "Asia/Yangon", 3),
"VTE": ("Vientiane", "Wattay", "LA", 17.99, 102.56, "Asia/Vientiane", 3),

# ---------------- ASIE DU SUD ----------------
"DEL": ("Delhi", "Indira Gandhi", "IN", 28.56, 77.10, "Asia/Kolkata", 1),
"BOM": ("Mumbai", "Chhatrapati Shivaji", "IN", 19.09, 72.87, "Asia/Kolkata", 1),
"BLR": ("Bangalore", "Kempegowda", "IN", 13.20, 77.71, "Asia/Kolkata", 2),
"MAA": ("Chennai", "Chennai", "IN", 12.99, 80.17, "Asia/Kolkata", 2),
"HYD": ("Hyderabad", "Rajiv Gandhi", "IN", 17.24, 78.43, "Asia/Kolkata", 3),
"CCU": ("Calcutta", "Netaji Subhas Chandra Bose", "IN", 22.65, 88.45, "Asia/Kolkata", 3),
"COK": ("Kochi", "Cochin", "IN", 10.15, 76.40, "Asia/Kolkata", 3),
"GOI": ("Goa", "Dabolim", "IN", 15.38, 73.83, "Asia/Kolkata", 3),
"KHI": ("Karachi", "Jinnah", "PK", 24.91, 67.16, "Asia/Karachi", 3),
"ISB": ("Islamabad", "Islamabad", "PK", 33.55, 72.83, "Asia/Karachi", 3),
"LHE": ("Lahore", "Allama Iqbal", "PK", 31.52, 74.40, "Asia/Karachi", 3),
"DAC": ("Dacca", "Shahjalal", "BD", 23.84, 90.40, "Asia/Dhaka", 3),
"CMB": ("Colombo", "Bandaranaike", "LK", 7.18, 79.88, "Asia/Colombo", 3),
"KTM": ("Katmandou", "Tribhuvan", "NP", 27.70, 85.36, "Asia/Kathmandu", 3),
"MLE": ("Malé", "Velana", "MV", 4.19, 73.53, "Indian/Maldives", 3),

# ---------------- MOYEN-ORIENT ----------------
"DXB": ("Dubaï", "Dubaï International", "AE", 25.25, 55.36, "Asia/Dubai", 1),
"AUH": ("Abu Dhabi", "Zayed", "AE", 24.43, 54.65, "Asia/Dubai", 1),
"SHJ": ("Charjah", "Charjah", "AE", 25.33, 55.52, "Asia/Dubai", 3),
"DOH": ("Doha", "Hamad", "QA", 25.27, 51.61, "Asia/Qatar", 1),
"RUH": ("Riyad", "Roi Khaled", "SA", 24.96, 46.70, "Asia/Riyadh", 1),
"JED": ("Djeddah", "Roi Abdulaziz", "SA", 21.68, 39.16, "Asia/Riyadh", 2),
"DMM": ("Dammam", "Roi Fahd", "SA", 26.47, 49.80, "Asia/Riyadh", 3),
"KWI": ("Koweït", "Koweït", "KW", 29.23, 47.97, "Asia/Kuwait", 3),
"BAH": ("Manama", "Bahreïn", "BH", 26.27, 50.63, "Asia/Bahrain", 3),
"MCT": ("Mascate", "Mascate", "OM", 23.59, 58.28, "Asia/Muscat", 3),
"AMM": ("Amman", "Queen Alia", "JO", 31.72, 35.99, "Asia/Amman", 3),
"TLV": ("Tel Aviv", "Ben Gourion", "IL", 32.01, 34.89, "Asia/Jerusalem", 1),
"BEY": ("Beyrouth", "Rafic Hariri", "LB", 33.82, 35.49, "Asia/Beirut", 3),
"IKA": ("Téhéran", "Imam Khomeini", "IR", 35.42, 51.15, "Asia/Tehran", 3),

# ---------------- AFRIQUE ----------------
"CAI": ("Le Caire", "Le Caire", "EG", 30.11, 31.41, "Africa/Cairo", 1),
"HRG": ("Hurghada", "Hurghada", "EG", 27.18, 33.80, "Africa/Cairo", 3),
"SSH": ("Charm el-Cheikh", "Charm el-Cheikh", "EG", 27.98, 34.39, "Africa/Cairo", 3),
"CMN": ("Casablanca", "Mohammed V", "MA", 33.37, -7.59, "Africa/Casablanca", 1),
"RAK": ("Marrakech", "Ménara", "MA", 31.61, -8.04, "Africa/Casablanca", 2),
"AGA": ("Agadir", "Al Massira", "MA", 30.38, -9.55, "Africa/Casablanca", 3),
"TNG": ("Tanger", "Ibn Battouta", "MA", 35.73, -5.92, "Africa/Casablanca", 3),
"FEZ": ("Fès", "Saïss", "MA", 33.93, -4.98, "Africa/Casablanca", 3),
"TUN": ("Tunis", "Carthage", "TN", 36.85, 10.23, "Africa/Tunis", 2),
"DJE": ("Djerba", "Zarzis", "TN", 33.88, 10.78, "Africa/Tunis", 3),
"ALG": ("Alger", "Houari Boumediene", "DZ", 36.69, 3.22, "Africa/Algiers", 2),
"ORN": ("Oran", "Ahmed Ben Bella", "DZ", 35.62, -0.62, "Africa/Algiers", 3),
"CZL": ("Constantine", "Mohamed Boudiaf", "DZ", 36.28, 6.62, "Africa/Algiers", 3),
"JNB": ("Johannesburg", "O. R. Tambo", "ZA", -26.14, 28.25, "Africa/Johannesburg", 1),
"CPT": ("Le Cap", "Le Cap", "ZA", -33.97, 18.60, "Africa/Johannesburg", 2),
"DUR": ("Durban", "Roi Shaka", "ZA", -29.61, 31.12, "Africa/Johannesburg", 3),
"NBO": ("Nairobi", "Jomo Kenyatta", "KE", -1.32, 36.93, "Africa/Nairobi", 1),
"MBA": ("Mombasa", "Moi", "KE", -4.03, 39.59, "Africa/Nairobi", 3),
"ADD": ("Addis-Abeba", "Bole", "ET", 8.98, 38.80, "Africa/Addis_Ababa", 1),
"LOS": ("Lagos", "Murtala Muhammed", "NG", 6.58, 3.32, "Africa/Lagos", 2),
"ABV": ("Abuja", "Nnamdi Azikiwe", "NG", 9.01, 7.26, "Africa/Lagos", 3),
"ACC": ("Accra", "Kotoka", "GH", 5.61, -0.17, "Africa/Accra", 3),
"DKR": ("Dakar", "Blaise Diagne", "SN", 14.67, -17.07, "Africa/Dakar", 2),
"ABJ": ("Abidjan", "Félix-Houphouët-Boigny", "CI", 5.26, -3.93, "Africa/Abidjan", 3),
"DAR": ("Dar es Salaam", "Julius Nyerere", "TZ", -6.87, 39.20, "Africa/Dar_es_Salaam", 3),
"EBB": ("Kampala", "Entebbe", "UG", 0.04, 32.44, "Africa/Kampala", 3),
"MRU": ("Port-Louis", "Sir S. Ramgoolam", "MU", -20.43, 57.68, "Indian/Mauritius", 2),
"SEZ": ("Victoria", "Seychelles", "SC", -4.67, 55.52, "Indian/Mahe", 3),
"TNR": ("Antananarivo", "Ivato", "MG", -18.80, 47.48, "Indian/Antananarivo", 3),

# ---------------- OCÉANIE ----------------
"SYD": ("Sydney", "Kingsford Smith", "AU", -33.94, 151.18, "Australia/Sydney", 1),
"MEL": ("Melbourne", "Tullamarine", "AU", -37.67, 144.84, "Australia/Melbourne", 1),
"BNE": ("Brisbane", "Brisbane", "AU", -27.38, 153.12, "Australia/Brisbane", 2),
"PER": ("Perth", "Perth", "AU", -31.94, 115.97, "Australia/Perth", 2),
"ADL": ("Adélaïde", "Adélaïde", "AU", -34.95, 138.53, "Australia/Adelaide", 3),
"OOL": ("Gold Coast", "Gold Coast", "AU", -28.16, 153.51, "Australia/Brisbane", 3),
"AKL": ("Auckland", "Auckland", "NZ", -37.01, 174.79, "Pacific/Auckland", 1),
"CHC": ("Christchurch", "Christchurch", "NZ", -43.49, 172.53, "Pacific/Auckland", 3),
"WLG": ("Wellington", "Wellington", "NZ", -41.33, 174.81, "Pacific/Auckland", 3),
"NAN": ("Nadi", "Nadi", "FJ", -17.76, 177.44, "Pacific/Fiji", 3),
}

# Pays : code ISO2 → (nom FR, [autres appellations acceptées])
COUNTRIES = {
"FR": ("France", ["france", "french republic"]),
"ES": ("Espagne", ["espagne", "spain", "espana", "españa"]),
"IT": ("Italie", ["italie", "italy", "italia"]),
"DE": ("Allemagne", ["allemagne", "germany", "deutschland"]),
"GB": ("Royaume-Uni", ["royaume-uni", "royaume uni", "uk", "united kingdom", "angleterre", "england", "grande-bretagne", "great britain", "ecosse", "scotland"]),
"GR": ("Grèce", ["grece", "greece", "hellas", "ellada"]),
"PT": ("Portugal", ["portugal"]),
"NL": ("Pays-Bas", ["pays-bas", "pays bas", "netherlands", "holland", "hollande"]),
"BE": ("Belgique", ["belgique", "belgium", "belgie"]),
"CH": ("Suisse", ["suisse", "switzerland", "schweiz", "helvetia"]),
"AT": ("Autriche", ["autriche", "austria", "osterreich"]),
"LU": ("Luxembourg", ["luxembourg"]),
"IE": ("Irlande", ["irlande", "ireland", "eire"]),
"DK": ("Danemark", ["danemark", "denmark"]),
"SE": ("Suède", ["suede", "sweden", "sverige"]),
"NO": ("Norvège", ["norvege", "norway", "norge"]),
"FI": ("Finlande", ["finlande", "finland", "suomi"]),
"IS": ("Islande", ["islande", "iceland"]),
"EE": ("Estonie", ["estonie", "estonia"]),
"LV": ("Lettonie", ["lettonie", "latvia"]),
"LT": ("Lituanie", ["lituanie", "lithuania"]),
"PL": ("Pologne", ["pologne", "poland", "polska"]),
"CZ": ("Tchéquie", ["tchequie", "republique tcheque", "czech republic", "czechia"]),
"HU": ("Hongrie", ["hongrie", "hungary", "magyarorszag"]),
"RO": ("Roumanie", ["roumanie", "romania"]),
"BG": ("Bulgarie", ["bulgarie", "bulgaria"]),
"HR": ("Croatie", ["croatie", "croatia", "hrvatska"]),
"RS": ("Serbie", ["serbie", "serbia"]),
"SK": ("Slovaquie", ["slovaquie", "slovakia"]),
"SI": ("Slovénie", ["slovenie", "slovenia"]),
"AL": ("Albanie", ["albanie", "albania"]),
"MK": ("Macédoine du Nord", ["macedoine", "macedoine du nord", "north macedonia"]),
"MT": ("Malte", ["malte", "malta"]),
"CY": ("Chypre", ["chypre", "cyprus"]),
"TR": ("Turquie", ["turquie", "turkey", "turkiye"]),
"RU": ("Russie", ["russie", "russia"]),
"US": ("États-Unis", ["etats-unis", "etats unis", "usa", "united states", "us", "amerique", "america"]),
"CA": ("Canada", ["canada"]),
"MX": ("Mexique", ["mexique", "mexico", "mejico"]),
"CU": ("Cuba", ["cuba"]),
"DO": ("République dominicaine", ["republique dominicaine", "dominican republic", "saint-domingue"]),
"PA": ("Panama", ["panama"]),
"CR": ("Costa Rica", ["costa rica"]),
"BR": ("Brésil", ["bresil", "brazil", "brasil"]),
"AR": ("Argentine", ["argentine", "argentina"]),
"CL": ("Chili", ["chili", "chile"]),
"PE": ("Pérou", ["perou", "peru"]),
"CO": ("Colombie", ["colombie", "colombia"]),
"EC": ("Équateur", ["equateur", "ecuador"]),
"UY": ("Uruguay", ["uruguay"]),
"JP": ("Japon", ["japon", "japan", "nippon"]),
"KR": ("Corée du Sud", ["coree", "coree du sud", "south korea", "korea"]),
"CN": ("Chine", ["chine", "china"]),
"HK": ("Hong Kong", ["hong kong", "hongkong"]),
"MO": ("Macao", ["macao", "macau"]),
"TW": ("Taïwan", ["taiwan", "taiwan", "formose"]),
"SG": ("Singapour", ["singapour", "singapore"]),
"TH": ("Thaïlande", ["thailande", "thailand"]),
"MY": ("Malaisie", ["malaisie", "malaysia"]),
"ID": ("Indonésie", ["indonesie", "indonesia"]),
"PH": ("Philippines", ["philippines"]),
"VN": ("Vietnam", ["vietnam", "viet nam"]),
"KH": ("Cambodge", ["cambodge", "cambodia"]),
"MM": ("Birmanie", ["birmanie", "myanmar", "burma"]),
"LA": ("Laos", ["laos"]),
"IN": ("Inde", ["inde", "india"]),
"PK": ("Pakistan", ["pakistan"]),
"BD": ("Bangladesh", ["bangladesh"]),
"LK": ("Sri Lanka", ["sri lanka", "ceylan"]),
"NP": ("Népal", ["nepal"]),
"MV": ("Maldives", ["maldives"]),
"AE": ("Émirats arabes unis", ["emirats", "emirats arabes unis", "uae", "united arab emirates"]),
"QA": ("Qatar", ["qatar"]),
"SA": ("Arabie saoudite", ["arabie saoudite", "saudi arabia", "arabie"]),
"KW": ("Koweït", ["koweit", "kuwait"]),
"BH": ("Bahreïn", ["bahrein", "bahrain"]),
"OM": ("Oman", ["oman"]),
"JO": ("Jordanie", ["jordanie", "jordan"]),
"IL": ("Israël", ["israel"]),
"LB": ("Liban", ["liban", "lebanon"]),
"IR": ("Iran", ["iran", "perse"]),
"EG": ("Égypte", ["egypte", "egypt"]),
"MA": ("Maroc", ["maroc", "morocco"]),
"TN": ("Tunisie", ["tunisie", "tunisia"]),
"DZ": ("Algérie", ["algerie", "algeria"]),
"ZA": ("Afrique du Sud", ["afrique du sud", "south africa"]),
"KE": ("Kenya", ["kenya"]),
"ET": ("Éthiopie", ["ethiopie", "ethiopia"]),
"NG": ("Nigeria", ["nigeria", "nigeria"]),
"GH": ("Ghana", ["ghana"]),
"SN": ("Sénégal", ["senegal"]),
"CI": ("Côte d'Ivoire", ["cote d'ivoire", "cote divoire", "ivory coast"]),
"TZ": ("Tanzanie", ["tanzanie", "tanzania"]),
"UG": ("Ouganda", ["ouganda", "uganda"]),
"MU": ("Maurice", ["maurice", "ile maurice", "mauritius"]),
"SC": ("Seychelles", ["seychelles"]),
"MG": ("Madagascar", ["madagascar"]),
"AU": ("Australie", ["australie", "australia"]),
"NZ": ("Nouvelle-Zélande", ["nouvelle-zelande", "nouvelle zelande", "new zealand"]),
"FJ": ("Fidji", ["fidji", "fiji"]),
}

# Exonymes et graphies locales : "saisie" -> nom de ville tel que stocké dans A
CITY_ALIASES = {
"koln":"Cologne","cologne":"Cologne","muenchen":"Munich","munchen":"Munich","munich":"Munich",
"wien":"Vienne","vienna":"Vienne","roma":"Rome","firenze":"Florence","venezia":"Venise",
"napoli":"Naples","torino":"Turin","milano":"Milan","genova":"Milan","sevilla":"Séville",
"seville":"Séville","lisboa":"Lisbonne","lisbon":"Lisbonne","porto":"Porto","praha":"Prague",
"prague":"Prague","warszawa":"Varsovie","warsaw":"Varsovie","krakow":"Cracovie","cracow":"Cracovie",
"moskva":"Moscou","moscow":"Moscou","athina":"Athènes","athens":"Athènes","thessaloniki":"Thessalonique",
"salonique":"Thessalonique","iraklio":"Héraklion","heraklion":"Héraklion","santorini":"Santorin",
"mykonos":"Mykonos","corfu":"Corfou","kerkyra":"Corfou","rhodes":"Rhodes","rodos":"Rhodes",
"kobenhavn":"Copenhague","copenhagen":"Copenhague","goteborg":"Göteborg","gothenburg":"Göteborg",
"stockholm":"Stockholm","oslo":"Oslo","helsinki":"Helsinki","reykjavik":"Reykjavik",
"brussel":"Bruxelles","brussels":"Bruxelles","antwerpen":"Bruxelles","beograd":"Belgrade",
"bucuresti":"Bucarest","bucharest":"Bucarest","sofia":"Sofia","zagreb":"Zagreb",
"geneva":"Genève","genf":"Genève","zuerich":"Zurich","basel":"Bâle","bale":"Bâle",
"nuernberg":"Nuremberg","nurnberg":"Nuremberg","hannover":"Hanovre","frankfurt":"Francfort",
"duesseldorf":"Düsseldorf","hamburg":"Hambourg","edinburgh":"Édimbourg","londra":"Londres",
"london":"Londres","lisbonne":"Lisbonne","valencia":"Valence","palma de mallorca":"Palma",
"mallorca":"Palma","majorque":"Palma","ibiza":"Ibiza","malaga":"Malaga","las palmas":"Las Palmas",
"grande canarie":"Las Palmas","tenerife":"Tenerife","saint jacques de compostelle":"Saint-Jacques-de-Compostelle",
"beijing":"Pékin","peking":"Pékin","shanghai":"Shanghai","guangzhou":"Canton","canton":"Canton",
"tokio":"Tokyo","osaka":"Osaka","kyoto":"Osaka","seoul":"Séoul","soul":"Séoul","busan":"Busan",
"bombay":"Mumbai","mumbai":"Mumbai","madras":"Chennai","chennai":"Chennai","calcutta":"Calcutta",
"kolkata":"Calcutta","bangalore":"Bangalore","bengaluru":"Bangalore","new delhi":"Delhi",
"saigon":"Hô Chi Minh-Ville","ho chi minh":"Hô Chi Minh-Ville","ho chi minh ville":"Hô Chi Minh-Ville",
"hanoi":"Hanoï","manila":"Manille","bangkok":"Bangkok","phuket":"Phuket","bali":"Bali",
"denpasar":"Bali","singapore":"Singapour","kuala lumpur":"Kuala Lumpur",
"cairo":"Le Caire","le caire":"Le Caire","alexandrie":"Le Caire","marrakesh":"Marrakech",
"casablanca":"Casablanca","tanger":"Tanger","tangier":"Tanger","fes":"Fès","fez":"Fès",
"joburg":"Johannesburg","johannesbourg":"Johannesburg","capetown":"Le Cap","cape town":"Le Cap",
"durban":"Durban","nairobi":"Nairobi","addis abeba":"Addis-Abeba","addis ababa":"Addis-Abeba",
"dubai":"Dubaï","dubay":"Dubaï","abou dhabi":"Abu Dhabi","doha":"Doha","riyad":"Riyad",
"riyadh":"Riyad","jeddah":"Djeddah","djeddah":"Djeddah","muscat":"Mascate","manama":"Manama",
"tel aviv":"Tel Aviv","beyrouth":"Beyrouth","beirut":"Beyrouth","teheran":"Téhéran",
"new york city":"New York","nyc":"New York","los angeles":"Los Angeles","san francisco":"San Francisco",
"washington dc":"Washington","philadelphia":"Philadelphie","philadelphie":"Philadelphie",
"detroit":"Détroit","montreal":"Montréal","quebec":"Montréal","vancouver":"Vancouver",
"mexico city":"Mexico","ciudad de mexico":"Mexico","cancun":"Cancún","la havane":"La Havane",
"havana":"La Havane","sao paulo":"São Paulo","rio":"Rio de Janeiro","brasilia":"Brasilia",
"buenos aires":"Buenos Aires","santiago du chili":"Santiago","lima":"Lima","bogota":"Bogota",
"quito":"Quito","montevideo":"Montevideo","sydney":"Sydney","melbourne":"Melbourne",
"auckland":"Auckland","wellington":"Wellington","papeete":"Papeete","tahiti":"Papeete",
"saint denis":"Saint-Denis","la reunion":"Saint-Denis","reunion":"Saint-Denis",
"pointe a pitre":"Pointe-à-Pitre","guadeloupe":"Pointe-à-Pitre","fort de france":"Fort-de-France",
"martinique":"Fort-de-France","ajaccio":"Ajaccio","corse":"Ajaccio","bastia":"Bastia",
"istanbul":"Istanbul","antalya":"Antalya","izmir":"Izmir","ankara":"Ankara","bodrum":"Bodrum",
}
